### ISSUE TITLE
Compile Fails on Fresh Install

### ISSUE THREAD

**Issue by spiegela** [inaka/sumo_db#112]
A fresh clone of the repo (post 0.1.4 tag) doesn't compile with rebar:

```shellsession
Compiling src/sumo_store_pgsql.erl failed:
src/sumo_store_pgsql.erl:24: can't find include lib "pgsql/include/pgsql.hrl"
src/sumo_store_pgsql.erl:262: record column undefined
ERROR: compile failed while processing /Users/spiegela/src/dist/spiegela-sumo_db: rebar_abort
```

I've done a bit of research, and I don't find a `pgsql.hrl` file in the [pgsql project](https://github.com/semiocast/pgsql).  The Column record that we're looking for [here](https://github.com/inaka/sumo_db/blob/master/src/sumo_store_pgsql.erl#L262) looks like the one referenced in the [epgsql project](https://github.com/epgsql/epgsql), but the include file is named `epgsql.hrl`.

Maybe this is pointing to an internal repo somewhere?

**Comment by jfacorro** [comment]
@spiegela `sumo_db` is using the [`epgsql/epgsql`](https://github.com/epgsql/epgsql) as a dependency in its 2.0.0 version which does contain the [pgsql.hrl](https://github.com/epgsql/epgsql/blob/2.0.0/include/pgsql.hrl) but seems to have been renamed in the latest version. Since these days we are mostly using `erlang.mk` to build our project we missed to add the dependency in the `rebar.config` file. We will add the dependency, thanks for reporting this!

**Comment by spiegela** [comment]
Thanks, @jfacorro!
