### ISSUE TITLE
Have the riak store create bucket types in create_schema

### ISSUE THREAD

**Issue by igaray** [inaka/sumo_db#145]
Currently the riak store create_schema does not fulfill its responsibility of preparing the storage for the data. The bucket type creation and  activation, index creation and association to the bucket must be done manually through the riak-admin command and riak's REST API. 

It would be preferable to handle this automatically, possibly tuning it via create_schema option parameters.

**Comment by jonasrichard** [comment]
Here you can find the `riak-admin` features:
[riak_core_console](https://github.com/basho/riak_core/blob/develop/src/riak_core_console.erl)
Unfortunately I don't know where Riak handles REST api, how they work, who can register to webmachine, etc.
Let me ask Basho if they accept pull requests (to documentation as well). If it works and add valuable features I think they are willing to merge.

**Comment by jfacorro** [comment]
What I found when I looked at this is that the [riak erlang client](https://github.com/inaka/riak-erlang-client.git) doesn't provide an API call to create `bucket types` because the (**Riak API**)[http://docs.basho.com/riak/latest/dev/references/http/#Bucket-related-Operations] doesn't provide one.

The [`riak-admin`](https://github.com/basho/riak/blob/56438479c912b1f8fcb6898717cd378b3c09d120/rel/files/riak-admin#L602) tool is built on a set of scripts that ends up making an [`rpc:call/3`]() to the [riak_kv_console:bucket_type_create/2](https://github.com/basho/riak_kv/blob/develop/src/riak_kv_console.erl#L502). As far as I could tell this is not exposed anywhere through the Riak API (either HTTP or ProtoBuff) which makes it hard to create buckets types and buckets.

**Comment by lixen** [comment]
Created a branch with create and activate bucket type API over PB.

git clone https://github.com/lixen/riak
git checkout bucket_types
make stagedevrel DEVNODES=1
./dev/dev1/bin/riak start

git clone https://github.com/lixen/riak-erlang-client
git checkout bucket_types
RIAK_TEST_NODE_1=dev1@127.0.0.1 RIAK_TEST_PBC_1=10017 make test

riakc_pb_socket:create_bucket_type(Pid, BucketType, BucketProps)
riakc_pb_socket:activate_bucket_type(Pid, BucketType)

**Comment by elbrujohalcon** [comment]
@lixen have you sent PRs with that to Basho?

**Comment by lixen** [comment]
@elbrujohalcon  I started with the riak-erlang-client. Do you have any requirement on Riak version where you would like this functionality?

**Comment by igaray** [comment]
We're currently using 2.0.5

**Comment by cabol** [comment]
This issue was moved to the specific Riak adapter repo [HERE](https://github.com/inaka/sumo_db_riak/issues/24)
