### ISSUE TITLE
Fix `find_by` function in `sumo_store_riak` to return all results when no pagination parameters are specified

### ISSUE THREAD

**Issue by cabol** [inaka/sumo_db#176]
Apparently Riak Search has configures some default pagination settings, so when you call `sumo:find_by(Doc, [])` it should return all documents, but currently is limited by 10. The idea is handle this from `sumo_store_riak` and return all results when pagination parameters are not being specified.

**Comment by igaray** [comment]
The rows parameter, already supported by sumo as limit/offset (rows/start), is the correct way to override this value. Solr does not provide a way to remove the default. 

Sumo's riak store behavior should be: if no limit/offset is passed, then default to N and 0.

There are two possibilities for N: 
1. hard-code a high value which will be passed as the rows parameter value when constructing queries. This value is hard to determine, since the max allowed value by solr (2147483391) is too high for some machines, causing the JVM to emit an  OOM exception (it apparently tries to preallocate memory for the query)
2. make this value configurable via sumo's config. if this is the case, it should it be riak-backend--specific

**Comment by igaray** [comment]
@elbrujohalcon When you have the time please comment

**Comment by elbrujohalcon** [comment]
@igaray considering that preallocation thingy… can you easily obtain the total number of rows from Riak before issuing the query… and use that? Will that be too bad for performance?

**Comment by igaray** [comment]
Not before issuing the query, as I suspect that the query has to be run to know how many possible matching documents there are. 
Another option I'm favoring now is running two queries behind the scenes:
when a find_by query without specified Limit and Offset is run, the first will get the first 10 results. If the `num_found` field of the riakc `search_result` record is > than 10, a second query will be made with start = 11 and rows = num_found - 10, and the results appended to the first 10 before being returned to the user.

**Comment by elbrujohalcon** [comment]
@igaray isn't this already solved?

**Comment by cabol** [comment]
@elbrujohalcon I think it was solved, take a look at: https://github.com/inaka/sumo_db_riak/blob/master/src/sumo_store_riak.erl
Can we close it?

**Comment by elbrujohalcon** [comment]
yes
