### ISSUE TITLE
Add generic type custom()

### ISSUE THREAD

**Issue by davecaos** [inaka/sumo_db#186]
This new type will be defined by the user.

**Comment by cabol** [comment]
I think this commit solves this issue: https://github.com/inaka/sumo_db/commit/9232d40a623fd802770af7ed5c4a00170489b76d
@elbrujohalcon @davecaos can we close this issue?

**Comment by elbrujohalcon** [comment]
@cabol it does, but please open corresponding issues in the different driver repos to make sure all of them deal with this field type

**Comment by elbrujohalcon** [comment]
@cabol have you read my previous comment? If so, please link all the issues to esl/TODO#58 in their descriptions

**Comment by cabol** [comment]
@elbrujohalcon the only driver/adapter with this requirement was Riak (and this is handled by Riak adapter), and this came from the nested objects feature we added to Riak adapter. Other adapters different to Riak are not using this type, therefore, they don't have issues related to this. So, do you want me to open the issue for all adapters anyways?

**Comment by elbrujohalcon** [comment]
@cabol they don't have issues, but since you're introducing this change in a global level you have to make sure that _if this is used_, it actually works and doesn't crash your system.

**Comment by elbrujohalcon** [comment]
@cabol for instance, I would like mnesia driver to store data _as is_ (i.e. tuples, atoms, even pids) in  _custom_ fields. Maybe _MySQL_ can use  `term_to_binary` / `binary_to_term`, etc…

Every driver must have _some_ implementation for dealing with this new field type. Otherwise they'll not support a totally valid data type and that's not good.

**Comment by cabol** [comment]
@elbrujohalcon ok, understood!
