### ISSUE TITLE
Riak store change type in maps

### ISSUE THREAD

**Issue by Euen** [inaka/sumo_db#199]
Riak store changes map's keys to atoms in sumo:find_all(module).

```erlang
R1 = module:create(<<"id">>, <<"label">>, #{<<"Key1">> => <<"val1">>,<<"Key2">> => <<"val2">>}),
% Fail because sumo:find_all/1 returns 
% <<"id">>, <<"label">>, #{'Key1' => <<"val1">>, 'Key2' => <<"val2">>}
  [R1] = sumo:find_all(module), % Fail

```

**Comment by cabol** [comment]
I'm not sure if this might be considered as an issue, since `sumo` hasn't notion about what a `map` is, this type not even exist. Currently, Riak's store is assuming nested entities as sumo models, that's the reason why those fields are being transformed to atoms (following the sumo API). Otherwise, how can we know when a nested entity has to be treated as a map and when as a sumo entity? We would need, for instance, create another data type in sumo, e.g.: `map`. There is an issue related with "custom" types (https://github.com/inaka/sumo_db/issues/186), probably this is the way, once this issue is done, we can do something here.

**Comment by cabol** [comment]
It was moved to https://github.com/inaka/sumo_db_riak/issues/4
