### ISSUE TITLE
All riak attribute map to string in Solr

### ISSUE THREAD

**Issue by emnvn** [inaka/sumo_db#207]
Hi all,

I m using sumo_db work with riak, I have defined this schema:

```erlang
-opaque balance() ::
  #{

        id  => binary(),
        account_id  => binary(),
        currency_unit  => binary(),
        amount  => integer(),
        pending_amount => integer(),
        created_by => binary(),
        created_time => datetime()
  }.

-spec sumo_schema() -> sumo:schema().
sumo_schema() ->
  sumo:new_schema(?MODULE, [
    sumo:new_field(id, string, [not_null, id]),
    sumo:new_field(account_id, string, [ not_null]),
    sumo:new_field(currency_unit, string, [not_null]),
    sumo:new_field(amount, integer),
    sumo:new_field(pending_amount, integer),
    sumo:new_field(created_by, string,  [not_null]),
    sumo:new_field(created_time, datetime,  [not_null])
  ]).
```
when I save data to riak, I found that all field are stored in binary data. The result that I can not search base on the amount attribute's integer value. It only search by string, not integer value.

For example, I want to get all record which amount [10 TO 50] but the record with amount = 120 also returned

I have make some research, i think the problem because i use default schema for Solr index https://raw.githubusercontent.com/basho/yokozuna/develop/priv/default_schema.xml

I think all integer field must suffix with _i but I see all fields are suffix with _register. It may the reason all field are string value, not a integer value.

I don't know how to define my integer field.

Thanks for helping.

**Comment by elbrujohalcon** [comment]
@emnvn I want the same thing! It's related to #201 and #206, but I will keep this issue open to check out that suffix info you provided. Thank you for that!

**Comment by cabol** [comment]
There is a big problem here, since we're using "Riak Data Types" in this Riak store, and at the same time we use 'maps' to manipulate entities, and the attributes on those maps are being mapped as 'registers', which are binaries, and here is where the problem is. Due to this, we aren't able to search by range of integers, e.g.: `[{'and', [{age, '>', 1}, {age, '<', 50}]}]`, because the field `age` is a register (binary). The only way to handle integers in Riak Data Types, is using counters, and this is not implemented because in counters, you cannot assign specific values, you just can increase or decrease the counter, so in some cases will be good but for other not. In conclusion, this is a disadvantage of Riak store in sumo due to the adopted implementation using Data Types.

**Comment by elbrujohalcon** [comment]
@cabol agreed.

**Comment by emnvn** [comment]
Hello,

I have resolved my problems by re-define search schema.
For example:
<dynamicField name="*_i_register"  type="int"    indexed="true"  stored="true"  multiValued="false"/>
<dynamicField name="*_f_register"  type="float"  indexed="true"  stored="true"  multiValued="false"/>
<dynamicField name="*_dt_register"  type="date"    indexed="true"  stored="true" multiValued="false"/>
...
This solved my problem.

**Comment by cabol** [comment]
Hi @emnvn, I'm glad you were able to find a way to deal with this issue. On other hand, I suppose you changed the existing yokozuna search schema directly from Riak right? I'm asking you because if you see the code of the Sumo Riak adapter, it points to yokozuna (it's hard-coded). If so, the thing with this solution is that to be able to use `sumo` with Riak, users must do an extra config steps, which I don't think be a bad thing at all, but it just to understand well what things/steps needs to be done to use your solution, and evaluate if it might be feasible.

So, I stay tuned! and THANKS!! Good suggestion!
