### ISSUE TITLE
Remove the need for mnesia's start_phase magic

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/sumo_db#275]
We do the following in each project where we use mnesia backend:

``` erlang
start_phase(create_schema, _StartType, []) ->
  Node = node(),
  _ = application:stop(mnesia),
  case mnesia:create_schema([Node]) of
    ok -> ok;
    {error, {Node, {already_exists, Node}}} -> ok
  end,
  ok = application:start(mnesia),
  sumo:create_schema();
```

We shouldn't need to do that. That should be part of the backend's `create_schema` function. We should only need to do…

``` erlang
start_phase(create_schema, _StartType, []) ->
  sumo:create_schema();
```

**Comment by cabol** [comment]
@elbrujohalcon I agree with you, but what I don't like is that `create_schema` runs for each model, so if we add that logic to the function, it will be executed for each repo as well, and it is unnecessary, because we only need to execute it once. My  suggestion is, what if we add that initialization part within the backend, in the `init` callback?

**Comment by elbrujohalcon** [comment]
@cabol 100% agree with you.
